openapi: 3.0.0
info:
  title: API Server
  version: 1.0.0
  description: API for student info

paths:
  /api/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  example: 4
                username:
                  type: string
                  example: "bob"
                password:
                  type: string
                  example: "bobaurmom123"
                email:
                  type: string
                  example: "bobaurmom@example.com"
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  username:
                    type: string
                    example: "boba"
                  password:
                    type: string
                    example: "bobaurmom123"
        '400':
          description: Bad Request
        '401':
          description: Unauthorized

  /api/login:
    post:
      summary: Login a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "boba"
                password:
                  type: string
                  example: "bobaurmom123"
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid credentials